# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
- id: crane
  env:
  - CGO_ENABLED=0
  main: ./cmd/crane/main.go
  binary: crane
  flags:
  - -trimpath
  ldflags:
    - -s
    - -w
    - -X github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Version}}
    - -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version={{.Version}}
  goarch:
    - amd64
  goos:
    - linux
    - windows
  ignore:
    - goos: windows
      goarch: 386